/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Principal;

import Controlador.LibreriaBDControlador;
import Controlador.LibreriaToolsControlador;
import Modelo.TextPrompt;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Christian Olmedo
 * @Objetive Inicia el proceso de validación de usuario y acceso al sistema
 * @Date 21/03/2020
 */
public class accesoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Acceso
     */
    private String Usuario = ""; //Inicializo el usuario //JLCI 23/03/2020
    private String Password = "";//
    /*Inicia importo las librerias basicas para validar el usuario
    Jose Luis Caamal Ic 28/06/2020
    */
    LibreriaToolsControlador lbt = new LibreriaToolsControlador();
    LibreriaBDControlador lbd = new LibreriaBDControlador();
    /*Termina la validación de la libreria*/
    /*Obtengo la lista de usuarios.. Jose Luis Caamal Ic 28/06/2020*/
    List <Object> listaDatosUsuarios = new ArrayList<Object>(); //Cargo una lista JLCI 28/06/2020 :D
        
    public accesoPrincipal() {
        initComponents();
        TextPrompt placeholder = new TextPrompt("Usuario",campoUsuario);
        TextPrompt placeholderPass = new TextPrompt("Password", jPasswordField1);
    /*Calendar cal = Calendar.getInstance();  //Llama la libreria de fechas
      //  java.util.Date fecha = cal.getTime(); //Toma el tiempo actual
        DateFormat formatterTime = DateFormat.getDateTimeInstance();//Toma la fecha actual
        etiquetaFecha.setText(formatterTime.format(fecha));*/
    /**
 *
 * @author Saul Arenas 
 * @Objetive Actualizar la fecha de acuerdo al sistema cada segundo.
 * @Date 10/06/2020
 */

    DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        etiquetaHora.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        botonInicioSesion = new javax.swing.JButton();
        etiquetaHora = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        labelNotificacionError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gas Valid 2.0");
        setLocation(new java.awt.Point(600, 200));
        setMinimumSize(new java.awt.Dimension(470, 688));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel1.setText("Bienvenido a GasValid 2.0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/gasvalidPrincipal.jpeg"))); // NOI18N

        campoUsuario.setBackground(new java.awt.Color(204, 204, 255));

        botonInicioSesion.setBackground(new java.awt.Color(153, 204, 255));
        botonInicioSesion.setText("Iniciar Sesión");
        botonInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioSesionActionPerformed(evt);
            }
        });

        etiquetaHora.setText("Hora");

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 255));

        labelNotificacionError.setBackground(new java.awt.Color(204, 255, 204));
        labelNotificacionError.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        labelNotificacionError.setForeground(new java.awt.Color(204, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Copia de user_group.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/blue_key.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etiquetaHora)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(botonInicioSesion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelNotificacionError)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(botonInicioSesion)
                .addGap(44, 44, 44)
                .addComponent(labelNotificacionError)
                .addGap(53, 53, 53)
                .addComponent(etiquetaHora)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioSesionActionPerformed
        // TODO add your handling code here:
        int validaResp = 0; //valida los resultados de la constula jlci 28/06/2020
        Usuario = campoUsuario.getText();
        Password = jPasswordField1.getText();
        Password = lbt.obtenerMD5(Password);
        /*Inicia: Se añade la validación del sistema para que se obtenga la información del usuario
        de manera global usaremos el modeloTablas Jose Luis Caamal Ic 28/06/2020 */
        lbd.openConnection();
        listaDatosUsuarios = lbd.obtenerDatosUsuario("tabla_usuarios", Usuario, Password);
        System.out.println("listaDatosUsuarios tamaño obtenido: "+listaDatosUsuarios.size()+"\nbotonInicioSesionActionPerformed :"+listaDatosUsuarios);
        lbd.closeConnection();
        validaResp = listaDatosUsuarios.size();
        //Hay que añadir md5 para comparar la contraseña actual con la insertada // JLCI 23/08/2020
        /*Se validan con usuarios temporales*/
        if(validaResp != 0){
//            if(Usuario.equals("gasvalid") && Password.equals("gasvalid")){
                //Inicia: Se obtienen toda la información del usuario en modelo Tablas JLCI 28/06/2020
                
                //lbt.obtenerDatosUsuarioGlobal(listaDatosUsuarios);
                //Imprimo mis datos del modeloTablas para verificar que ya los tenga
                //lbd.mt.toString();
                //Para recuperar el usuario se valida con lo siguiente lbd.mt.toString
                System.out.println(lbd.mtu.toString());
                //Termina.
                ventanaPrincipal ventanaPrincipal = new ventanaPrincipal(lbd.mtu);
                this.dispose();
                ventanaPrincipal.show();
//            }
//            else{
//                System.out.println("Verifica tu usuario y contraseña.");
//                labelNotificacionError.setText("Verifica tu usuario y contraseña.");
//                //Añadir un log de errores
//            }
        }else{
                System.out.println("No existe el usuario.");
                labelNotificacionError.setText("No existe el usuario.\nVerifica tu usuario y contraseña.");
                //Añadir un log de errores
            }
    }//GEN-LAST:event_botonInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(accesoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//        </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new accesoPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicioSesion;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiquetaHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel labelNotificacionError;
    // End of variables declaration//GEN-END:variables
}
