/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Principal;

import Vista.Cronometros.catalogoCronometro;
import Vista.Jarras.catalogoMedidadVolumetricasJarras;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yuliana adame
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    String ruta = "";
    public URL url = getClass().getResource(ruta);
    Image image = new ImageIcon(url).getImage();
    
    public ventanaPrincipal() {
        initComponents();
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        catalogoCronometros = new javax.swing.JButton();
        catalogoJarras = new javax.swing.JButton();
        catalogoTermometros = new javax.swing.JButton();
        catalogoHologramas = new javax.swing.JButton();
        capturaEstacion = new javax.swing.JButton();
        movimientoDispensarios = new javax.swing.JButton();
        registroSolicitud = new javax.swing.JButton();
        registoContrato = new javax.swing.JButton();
        inspeccionMedicion = new javax.swing.JButton();
        inspeccionMedicion1 = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));
        jPanel1.setAlignmentX(60.0F);
        jPanel1.setAlignmentY(60.0F);

        catalogoCronometros.setIcon(new javax.swing.ImageIcon("C:\\Users\\Personal\\Dropbox\\GasValid2.0\\Codigo\\GasValid2P0\\src\\Multimedia\\cronometro_opt.png")); // NOI18N
        catalogoCronometros.setAlignmentX(0.5F);
        catalogoCronometros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoCronometrosActionPerformed(evt);
            }
        });

        catalogoJarras.setIcon(new javax.swing.ImageIcon("C:\\Users\\Personal\\Dropbox\\GasValid2.0\\Codigo\\GasValid2P0\\src\\Multimedia\\jarras_opt.png")); // NOI18N
        catalogoJarras.setAlignmentX(0.5F);
        catalogoJarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoJarrasActionPerformed(evt);
            }
        });

        catalogoTermometros.setIcon(new javax.swing.ImageIcon("C:\\Users\\Personal\\Dropbox\\GasValid2.0\\Codigo\\GasValid2P0\\src\\Multimedia\\termometro_de_gas (1)_opt.jpg")); // NOI18N
        catalogoTermometros.setAlignmentX(0.5F);
        catalogoTermometros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoTermometrosActionPerformed(evt);
            }
        });

        catalogoHologramas.setAlignmentX(0.5F);
        catalogoHologramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoHologramasActionPerformed(evt);
            }
        });

        capturaEstacion.setAlignmentX(0.5F);
        capturaEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturaEstacionActionPerformed(evt);
            }
        });

        movimientoDispensarios.setAlignmentX(0.5F);
        movimientoDispensarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimientoDispensariosActionPerformed(evt);
            }
        });

        registroSolicitud.setAlignmentX(0.5F);
        registroSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroSolicitudActionPerformed(evt);
            }
        });

        registoContrato.setIcon(new javax.swing.ImageIcon("C:\\Users\\Personal\\Dropbox\\GasValid2.0\\Codigo\\GasValid2P0\\src\\Multimedia\\contrato-de-diseno_opt.jpg")); // NOI18N
        registoContrato.setAlignmentX(0.5F);
        registoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registoContratoActionPerformed(evt);
            }
        });

        inspeccionMedicion.setAlignmentX(0.5F);
        inspeccionMedicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspeccionMedicionActionPerformed(evt);
            }
        });

        inspeccionMedicion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/gasvalid_changemain.png"))); // NOI18N
        inspeccionMedicion1.setAlignmentX(0.5F);
        inspeccionMedicion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspeccionMedicion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(capturaEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(movimientoDispensarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registroSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inspeccionMedicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFondo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(catalogoCronometros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(catalogoJarras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(catalogoTermometros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(catalogoHologramas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(registoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inspeccionMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelFondo)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catalogoJarras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catalogoCronometros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catalogoTermometros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catalogoHologramas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capturaEstacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movimientoDispensarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registroSolicitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inspeccionMedicion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inspeccionMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catalogoCronometrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoCronometrosActionPerformed
    catalogoCronometro abrir = new catalogoCronometro();
    abrir.setVisible(true);
    this.setVisible(false);
        
    }//GEN-LAST:event_catalogoCronometrosActionPerformed
  
    private void catalogoJarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoJarrasActionPerformed
    catalogoMedidadVolumetricasJarras abrir = new catalogoMedidadVolumetricasJarras();
    abrir.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_catalogoJarrasActionPerformed

    private void catalogoTermometrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoTermometrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catalogoTermometrosActionPerformed

    private void catalogoHologramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoHologramasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catalogoHologramasActionPerformed

    private void capturaEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturaEstacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capturaEstacionActionPerformed

    private void movimientoDispensariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimientoDispensariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movimientoDispensariosActionPerformed

    private void registroSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroSolicitudActionPerformed

    private void registoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registoContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registoContratoActionPerformed

    private void inspeccionMedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inspeccionMedicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inspeccionMedicionActionPerformed

    
    /*
    Desarrollo: José Luis Caamal Ic
    Objetivo: El boton cambia la imagen del panel principal por cualquiera que se elija mediante el jfilechooser.
    Parametros:
    */
    private void inspeccionMedicion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inspeccionMedicion1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
    
            FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif"); 
            fileChooser.setFileFilter(imgFilter);

            int result = fileChooser.showOpenDialog(this);

            if (result != JFileChooser.CANCEL_OPTION) {

                File fileName = fileChooser.getSelectedFile();

                if ((fileName == null) || (fileName.getName().equals(""))) {
                    //txt.setText("...");
                } else {
                    //txt.setText(fileName.getAbsolutePath());
                    ruta = fileName.getAbsolutePath();
                    labelFondo.setIcon(new ImageIcon(ruta));
                    labelFondo.setOpaque(true);
                }
            }
    }//GEN-LAST:event_inspeccionMedicion1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ventanaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capturaEstacion;
    private javax.swing.JButton catalogoCronometros;
    private javax.swing.JButton catalogoHologramas;
    private javax.swing.JButton catalogoJarras;
    private javax.swing.JButton catalogoTermometros;
    private javax.swing.JButton inspeccionMedicion;
    private javax.swing.JButton inspeccionMedicion1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JButton movimientoDispensarios;
    private javax.swing.JButton registoContrato;
    private javax.swing.JButton registroSolicitud;
    // End of variables declaration//GEN-END:variables
}
