/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Usuarios;

import Controlador.LibreriaBDControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Saul
 */
public class Eliminar_Usuarios extends javax.swing.JDialog {

    /**
     * Creates new form Eliminar_Usuarios
     */
    int tipoUsuario = 0;
    LibreriaBDControlador lbc = new LibreriaBDControlador();
    public Eliminar_Usuarios(java.awt.Frame parent, boolean modal, int tipoUsuarioActual) {
        super(parent, modal);
        initComponents();
        this.tipoUsuario = tipoUsuarioActual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoIDElimina = new javax.swing.JTextField();
        EliminarELU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        jLabel9.setText("Eliminar Usuario");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("ID");

        campoIDElimina.setBackground(new java.awt.Color(200, 226, 236));
        campoIDElimina.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        EliminarELU.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        EliminarELU.setForeground(new java.awt.Color(153, 51, 0));
        EliminarELU.setText("Eliminar");
        EliminarELU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarELUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarELU)
                            .addComponent(campoIDElimina, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoIDElimina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(EliminarELU, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarELUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarELUActionPerformed
        String id = campoIDElimina.getText();
        int validoEliminaUsuario = 0;
        int validoAux = Integer.parseInt(id); //Convierte el id en entero
        System.out.println("EliminarELUActionPerformed tipoUsuario:"+tipoUsuario+"y id:"+id);
        if(tipoUsuario != validoAux){
            lbc.openConnection();
            validoEliminaUsuario = lbc.validaSiExisteUsuario("tabla_usuarios", id);
            if(validoEliminaUsuario == 1){
                validoEliminaUsuario = lbc.eliminarFila("tabla_usuarios",id);
                lbc.closeConnection();
                if(validoEliminaUsuario == 1 && !id.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Se elimino un usuario");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Por Favor, digita un ID valido.");
                }
            }
            else{
                    JOptionPane.showMessageDialog(rootPane, "No existe el usuario que quieres eliminar.");
             }
        }else{
            JOptionPane.showMessageDialog(rootPane, "No puedes eliminar tu propio usuario.");
        }
        
        
        this.setVisible(false);
    }//GEN-LAST:event_EliminarELUActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarELU;
    private javax.swing.JTextField campoIDElimina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
