/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Estacion;

import Controlador.LibreriaBDControlador;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joseluis.caamal
 */
public class catalogoEstaciones extends javax.swing.JFrame {

    /**
     * Creates new form catalogoEstaciones
     */
    public String columna[];
    DefaultTableModel modeloEstaciones;
    LibreriaBDControlador lbd = new LibreriaBDControlador();
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    public catalogoEstaciones() {
        lbd.openConnection();
        getColumnas();
        modeloEstaciones = lbd.modeloEstaciones(columna,"","",""); //Cargo el contenido por defecto
        lbd.closeConnection();
        initComponents();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int col = 0;
                if (row >= 0 && col >= 0) {
                    String valor = jTable1.getModel().getValueAt(row, col).toString(); //Tomo el valor de el modelo de la tabla
                    folioEstacion.setText(valor); //Obtengo el valor del textfield
                }
          }
        });
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTable1.setDefaultRenderer(String.class, centerRenderer);
    }
    
    /*Obtengo los titulos de mi tabla*/
    String[] getColumnas(){ //Columnas
            columna = new String[] {"ESTACION","FECHAREGISTRO",
            "NOMRESPONSABLE",
            "RAZONSOCIAL",
            "REGFEDCAUSANTE",
            "DOMICILIO",
            "COLONIA",
            "CIUDAD",
            "ESTADO",
            "TELEFONO",
            "EMAIL",
            "COORDENADASUTM",
            "CODIGOPOSTAL",
            "NUMEROCRE",
            "MARCAGASOLINA",
            "TOTALGMAGNA",
            "TOTALGDIESEL",
            "TOTALGPREMIUM",
            "ESTATUSMANGUERA"};
        return columna;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        AgregarEstacion = new javax.swing.JButton();
        ModificarEstacion = new javax.swing.JButton();
        EliminarEstacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        MostrarTodasCH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        folioEstacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tipoMGas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        estatusEstacion = new javax.swing.JComboBox();
        RefrescarCH = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1098, 591));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        AgregarEstacion.setText("Agregar Estación");
        AgregarEstacion.setFocusable(false);
        AgregarEstacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AgregarEstacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AgregarEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEstacionActionPerformed(evt);
            }
        });

        ModificarEstacion.setText("Modificar Estación ");
        ModificarEstacion.setFocusable(false);
        ModificarEstacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ModificarEstacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModificarEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEstacionActionPerformed(evt);
            }
        });

        EliminarEstacion.setText("Eliminar Estación");
        EliminarEstacion.setFocusable(false);
        EliminarEstacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EliminarEstacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EliminarEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEstacionActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        MostrarTodasCH.setForeground(new java.awt.Color(255, 0, 0));
        MostrarTodasCH.setText("Buscar");
        MostrarTodasCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodasCHActionPerformed(evt);
            }
        });

        jLabel3.setText("Núm. Estación:");

        jLabel1.setText("Marca Gasolina:");

        tipoMGas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pemex", "Oxxo Gas", "Mobil", "British Petroleum", "Repsol", "Shell", "Petro Seven", "G-500", "Hidrosina", "Akron", "Grupo Eco" }));

        jLabel2.setText("Estatus:");

        estatusEstacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIGENTE", "CANCELADO", "EN_REPARACION", "DESCONTINUADO", "FUERA_DE_SERVICIO", "ASIGNADA", "NO_ASIGNADA" }));

        RefrescarCH.setText("Refrescar");
        RefrescarCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(folioEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoMGas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estatusEstacion, 0, 1, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarTodasCH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefrescarCH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(folioEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MostrarTodasCH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tipoMGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(estatusEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(RefrescarCH)
                        .addContainerGap())))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("Para filtrar los campos primero deben \nañadir información a los campos y después \ndarle clic a buscar. Nota: Puede seleccionar\ndirectamente en la tabla para llenar el \nnúmerode estación en automatico.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AgregarEstacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarEstacion, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(EliminarEstacion, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AgregarEstacion)
                        .addGap(27, 27, 27)
                        .addComponent(ModificarEstacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliminarEstacion))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
        jTable1.setModel(modeloEstaciones);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEstacionActionPerformed
        agregarEstaciones ae = new agregarEstaciones(this, true);
        ae.show();
    }//GEN-LAST:event_AgregarEstacionActionPerformed

    private void ModificarEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEstacionActionPerformed
        modificarEstacion ae = new modificarEstacion(this, true);
        ae.show(true);
    }//GEN-LAST:event_ModificarEstacionActionPerformed

    private void EliminarEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEstacionActionPerformed
     eliminarEstacion ver=new eliminarEstacion(this, true);
     ver.show();
    }//GEN-LAST:event_EliminarEstacionActionPerformed

    private void MostrarTodasCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodasCHActionPerformed
        // TODO add your handling code here:
        String folioH = folioEstacion.getText();
        String tipoH = (String)tipoMGas.getSelectedItem();
        String estatusH = (String) estatusEstacion.getSelectedItem();
        lbd.openConnection();
        modeloEstaciones = lbd.modeloEstaciones(columna, tipoH, folioH, estatusH);
        lbd.closeConnection();
        jTable1.setModel(modeloEstaciones);
        modeloEstaciones.fireTableDataChanged();
        
    }//GEN-LAST:event_MostrarTodasCHActionPerformed

    private void RefrescarCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarCHActionPerformed
               lbd.openConnection();
        modeloEstaciones = lbd.modeloEstaciones(columna, "", "", "");
        lbd.closeConnection();
        jTable1.setModel(modeloEstaciones);
        modeloEstaciones.fireTableDataChanged();
    }//GEN-LAST:event_RefrescarCHActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarEstacion;
    private javax.swing.JButton EliminarEstacion;
    private javax.swing.JButton ModificarEstacion;
    private javax.swing.JButton MostrarTodasCH;
    private javax.swing.JButton RefrescarCH;
    private javax.swing.JComboBox estatusEstacion;
    private javax.swing.JTextField folioEstacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox tipoMGas;
    // End of variables declaration//GEN-END:variables
}
